services:
  api:
    build: .
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync
          path: .
          target: /rad-times
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
